language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.4
  - 2.3.1
  - ruby-head
  - jruby
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

sudo: required
dist: trusty
